[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
	let g:ctrlp_max_files = 1000
	let g:ctrlp_max_depth = 10
'''

[[plugins]]
repo = 'Shougo/neocomplete'
if = '''!has('nvim')'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = '''has('nvim')'''

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'
