[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'Shougo/neocomplete'
if = '''!has('nvim')'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = '''has('nvim')'''

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'vim-syntastic/syntastic'
if = ''' !has("nvim") '''

[[plugins]]
repo = 'neomake/neomake'
if = ''' has("nvim") '''
