[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python', 'python3']
if = ''' !has("nvim") '''

[[plugins]]
repo = 'deoplete-plugins/deoplete-jedi'
if = ''' has("nvim") '''
on_ft = ['python', 'python3']
depends = [ 'deoplete.nvim' ]

[[plugins]]
repo = 'vim-jp/cpp-vim'
on_ft = ['cpp', 'hpp', 'cxx']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'hdima/python-syntax'
on_ft = ['python', 'python3']

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex', 'latex', 'bib']

# [[plugins]]
# repo = 'rust-lang/rust.vim'
# on_ft = ['rust']

# [[plugins]]
# repo = 'racer-rust/vim-racer'
# on_ft = ['rust']

# [[plugins]]
# repo = 'deoplete-plugins/deoplete-go'
# on_ft = ['go']
# build = 'make'
# hook_post_source = '''
# let g:deoplete#sources#go#gocode_binary = $GOPATH.'/bin/gocode'
# let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
# '''

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown']

# [[plugins]]
# repo = "mhartington/nvim-typescript"
# on_ft = ["typescript"]
# build = "./install.sh"

# [[plugins]]
# repo = "HerringtonDarkholme/yats.vim"
# on_ft = ["typescript"]
