[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python', 'python3']
if = ''' !has("nvim") '''

[[plugins]]
repo = 'zchee/deoplete-jedi'
if = ''' has("nvim") '''
on_ft = ['python', 'python3']
depends = [ 'deoplete.nvim' ]

[[plugins]]
repo = 'vim-jp/cpp-vim'
on_ft = ['cpp', 'hpp', 'cxx']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
